/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComponentDemo: typeof import('./src/components/demo/ComponentDemo.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutSkeleton: typeof import('@nutui/nutui-taro')['Skeleton']
    PlateKeyBoard: typeof import('./src/components/PlateKeyBoard/PlateKeyBoard.vue')['default']
    PlateNoInput: typeof import('./src/components/PlateNoInput/PlateNoInput.vue')['default']
  }
}
